services:
  postgres:
    container_name: postgres_dep
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: department_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "1543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: